### ISSUE TITLE
Upload package to tagged release asset

### ISSUE THREAD

**Issue by ltcptgeneral** [titanscouting/red-alliance-analysis#55]
**Is your feature request related to a problem? Please describe.**
Currently, the package is built and uploaded to pypi on every tag, but the package wheel is not added as a release asset.

**Describe the solution you'd like**
Edit/add an action that takes the whl file generated from the existing publish to pypi action and uploads it to the tagged release asset.

**Additional context**
Example actions: https://github.com/actions/upload-release-asset

**Comment by devksingh4** [comment]
Fixed in c4e071b87b97174b8509d08735c13b84f628e217
